### PR TITLE
fix: cross-compatible method for setExepath

### PR DESCRIPTION
**Pull request by tekladis**
Some code cleanup for my last PR.  This gives native methods for both Windows and Unix-like operating systems to get the correct executable path.

### CODE REVIEW

**Comment by fabricecaruso** [comment]
You wanna cancel what you previously did ? Any reason ?

**Comment by tekladis** [comment]
This isn't a cancellation of what I did previously.  I just added the native Windows method and placed the code in setExePath.  Now argv[0] is used as a fallback in the event the platform-native methods fail to find the executable location.

It's mostly just cleanup and a method for the Windows platform to keep everything consistent. :)

**Comment by fabricecaruso** [comment]
Ok didn't read it all.

Don't do it that way ! 
What's the use of setExepath with a parameter if you never use the parameter ?
Can the platform-native methods really fail ? Under Windows, sure it will never fail (only if your buffer size is too small).

If you rely on GetModuleFileNameW/readlink methods (I totally can understand that), this code should be located in the getExePath method, not the set method. And then : the set method is not longer needed !

**Comment by tekladis** [comment]
Well I wasn't really sure if there were any edge cases where one of those might fail.  Chances are I was just overthinking it, lol.  Let me make a few small changes. :)

**Comment by fabricecaruso** [comment]
I don't know if readlink can fail on linux...

**Comment by fabricecaruso** [comment]
After some thoughs, I think your approach is fine

**Pull request merged**
