### PR TITLE
Fix: Make exePath on Linux more reliable

### PR DESCRIPTION
**Pull request by tekladis**
Just some very minor changes that allows package maintainers to retain the $prefix/bin and $prefix/share layout instead of bundling the resources together with the executable on Linux.

### CODE REVIEW

**Comment by fabricecaruso** [comment]
Hello, as I'm a windows developper, just explain to me :
- Is the readlink("/proc/self/exe") result different from argv[0] ? What's the need of it if the value is always the same ? Is there any possibility values are differents ?
- As "/share/emulationstation/resources/" does not exist on windows or other platforms, wouldn't it be better to : at least surround it with #if defined(__linux__), or, make the path configurable and modifiable in Settings ( doing that it could be reused for windows too ) ? ( something like Settings:getString("SharedResourcePath") ) ?

**Comment by tekladis** [comment]
On Linux, argv[0] typically contains the binary name without the full path.  I wrote a little test program that tests both.  The code is as follows:
```cpp
#include <cstdio>
#include <cstring>
#include <libgen.h>
#include <unistd.h>

int main(int argc, char* argv[])
{
    fprintf(stderr, "argv: %s\n", argv[0]);
    char* result = new char[4096];
    ssize_t len = readlink("/proc/self/exe", result, 4096);
    if (len != -1) {
        result[len] = 0;
        fprintf(stderr, "readlink: %s\n", result);
    }
    delete [] result;
    return 0;
}
```

Here is the resulting output:
```
argv: ./a.out
readlink: /home/justin/Projects/testing/a.out
```

So the only way you'll be getting the executable path using argv[0] is if you explicitly type out the full path on the command line.


As for your other point, I strongly agree.  I believe retroarch takes a very similar approach where basically all of it's directories (resources, cores, etc.) are configurable, with the exception of the configuration file itself.  The current way ES handles missing font resources is an assertion which causes the application to terminate with a very vague message.

I propose checking on startup and saving to the configuration accordingly.  This process should repeat in the event the resources directory goes missing or is moved.  If it's not found in any of the common directories, provide a small message telling the user to configure manually.  This would allow the most flexibility without forcing the user to configure manually for typical cases.

I'll remove the changes in ResourceManager and get that solution going in a separate PR.  That would just leave the readlink addition for this.  I mostly threw this together due to some packaging issues on Arch Linux, but I don't mind providing a better solution. :)

**Comment by fabricecaruso** [comment]
Ooops, you made it complex...

I can understand the readlink thing :
In the case you launch the process in a terminal when the current directory is the exe's directory, and run with "./emulationstation" - not using the full path - It is incomplete. Ok... Fine... It concerns only users running ES manually using a terminal... Why not...

But the Settings "ResourceDir" thing you did is very very very complex...
Plus, in my point of view, It should never be assigned by code the way you do it.

I imagine something simplest, using "ResourceDir" with a default path in settings, that can be changed by the user in the cfg file.

Imagine that kind of things :

- Settings.cpp :

```
#if WIN32
mStringMap["ResourceDir"] = "${exepath}/../resources"; // When using visual studio
#else // linux
mStringMap["ResourceDir"] = "${exepath}/share/emulationstation/resources";
#endif
```

 - ResourceManager::getResourcePath :

```
test = Utils::String::replace(Settings::getInstance()->getString("ResourceDir"), "${exepath}", Utils::FileSystem::getExePath()) + "/" + &path[2];
if(Utils::FileSystem::exists(test)) 
      return test;
```

And that's it... Why make it more complex than that ?

**Comment by tekladis** [comment]
Well ES will fail to start entirely without a working ResourceDir so I was just trying to catch most typical cases, lol.  I can definitely see where it looks more complex than it should be though.  I was just experimenting last night and forgot I had pushed this already.

I reverted to something less ridiculous for this PR.

Would you be against adding a compile time variable for cmake... such as DEFAULT_RESOURCE_DIR so the default directory can be set by package maintainers without having to make direct code modifications?

**Comment by fabricecaruso** [comment]
I can accept you PR (for the exepath thing), but :

There's nothing left about resources loading, you removed it all ?
Shall I wait for the PR to be complete ?

What about DEFAULT_RESOURCE_DIR ? 

What you propose for resources path has interest for Windows too (when working/debugging mostly)
The thing is : I don't want this variable to be required, not to change anything on the autobuild scripts.

It seems far easier to me for everyplatform looking relative to the exe's path in the code using settings...
But I may be wrong...

Propose, we'll discuss ;-)

**Comment by tekladis** [comment]
This PR is complete as-is, so you can go ahead and merge it if you like.

Basically DEFAULT_RESOURCE_DIR can be set when you invoke cmake, such as:
```
cmake -DDEFAULT_RESOURCE_DIR="../share/emulationstation/resources"
```
That'll be checked during compile time and used if it's set.  If it's not set we'll just use the defaults you proposed above.  This would make packaging easier while still keeping the code fairly simple.  When DEFAULT_RESOURCE_DIR is set we would use a relative path based on the executable location.  This should be useful to both Windows and Linux when distributing the package.

**Comment by tekladis** [comment]
To add to this, we should definitely still show an error message if the resource directory isn't found just to make it more user friendly.  It's better than the current behavior where an assertion causes the program to exit with a fairly obscure error message when the resource directory is missing.

**Pull request merged**
