### PR TITLE
fix build errors for ODROID

### PR DESCRIPTION
**Pull request by sana2dang**
added some source codes with using definition ODROID.

"/usr/lib/aarch64-linux-gnu/libMali.so" in the ODROID N2

### CODE REVIEW

**Comment by fabricecaruso** [comment]
I'm truly sorry but what you did is a very bad way to do things. 
Adding a new definition is not the good way to do that. 
Removing #ifdef _RPI_ for the #include is the good one.
In my recent commit, I have just fixed these two mistakes.

**Comment by sana2dang** [comment]
> I'm truly sorry but what you did is a very bad way to do things.
> Adding a new definition is not the good way to do that.
> Removing #ifdef _RPI_ for the #include is the good one.
> In my recent commit, I have just fixed these two mistakes.

Thank you for the advice.

I look forward to your good activities ^^

**Comment by fabricecaruso** [comment]
Sorry to have rejected your PR, this was nice from you.
The version should build now on Odroid too.
Still, I'm interested in your korean translation. Can you do a PR with it ?

**Comment by sana2dang** [comment]
> Sorry to have rejected your PR, this was nice from you.
> The version should build now on Odroid too.
> Still, I'm interested in your korean translation. Can you do a PR with it ?

I'm fine ^^

I'll try to RP as soon as possible.

**Pull request closed without merging**
